import Head from 'next/head'
import Header from '../components/shared/Header'
import Footer from '../components/shared/Footer'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import axios from 'axios'
import { Select, Typography, MenuItem, Button, Card } from '@mui/material'
import { Stack } from '@mui/system'
import { useRouter } from 'next/router'


export default function Home() {
	const [sabores, setSabores] = useState([]);
	const [massas, setMassas] = useState([]);
	const [bordas, setBordas] = useState([]);
	const { push } = useRouter();

	const [saboresSelecionados, setSaboresSelecionados] = useState([
		'none', 'none', 'none'	
	]);

	const [massaSelecionada, setMassaSelecionada] = useState('none');
	const [bordaSelecionada, setBordaSelecionada] = useState('none');

	useEffect(() => {
		const baseUrl = document.location.origin;
		axios.get(`${baseUrl}/api/sabores`)
			.then((response) => {
				setSabores(response.data);
			})
			.catch((error) => {
				console.log(error);
			})

		axios.get(`${baseUrl}/api/massas`)
			.then((response) => {
				setMassas(response.data);
			}
			)
			.catch((error) => {
				console.log(error);
			}
			)

		axios.get(`${baseUrl}/api/bordas`)
			.then((response) => {
				setBordas(response.data);
			}
			)
			.catch((error) => {
				console.log(error);
			}
			)
	}, []);

	const inserePizza = (pizza) => {
		const baseUrl = document.location.origin;
		axios.post(`${baseUrl}/api/pizzas`, {
			pizza: pizza
		})
			.then((response) => {	
				console.log(response);
				push('/pedidos/' + response.data.id);
			})
			.catch((error) => {
				console.log(error);
			})
	}

	return (
		<div>
			<Head>
				<title>Pizzaria dos guris</title>
				<meta name="description" content="Generated by Pizzaria dos guris" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header value="/" />
			
			<Stack spacing={2} direction="row" justifyContent="center" alignItems="center">
				<Card sx={{padding: 2, marginTop: 2}} >
					<Typography align="center" variant="h3">Monte sua pizza</Typography>

					<Typography align="center" variant="h4">Sabores (3 sabores)</Typography>

					<Stack direction="row" justifyContent="center" sx={{ width: '100%',
						'@media screen and (max-width: 768px)': {
							flexWrap: 'wrap'
						},
						marginTop: 2
					}}>
						<Select
							label="sabor1"
							id="sabor1"
							value={saboresSelecionados[0]}
							onChange={(event) => {
								const novoArray = [...saboresSelecionados];
								novoArray[0] = event.target.value;
								setSaboresSelecionados(novoArray);
							}}
							sx={{
								'@media screen and (max-width: 768px)': {
									width: '100%',
									marginBottom: 1,
									marginRight: 0		
								},
								marginRight: 1
							}}
						>
							<MenuItem value={'none'}>Selecione um sabor</MenuItem>
							{sabores.map((sabor) => (
								<MenuItem value={sabor.id}>{sabor.nome}</MenuItem>
							))}
						</Select>

						<Select
							label="sabor2"
							id="sabor2"
							value={saboresSelecionados[1]}
							onChange={(event) => {
								const novoArray = [...saboresSelecionados];
								novoArray[1] = event.target.value;
								setSaboresSelecionados(novoArray);
							}}
							sx={{
								'@media screen and (max-width: 768px)': {
									width: '100%',
									marginBottom: 1,
									marginRight: 0		
								},
								marginRight: 1
							}}
						>
							<MenuItem value={'none'}>Selecione um sabor</MenuItem>
							{sabores.map((sabor) => (
								<MenuItem value={sabor.id}>{sabor.nome}</MenuItem>
							))}
						</Select>

						<Select
							label="sabor3"
							id="sabor3"
							value={saboresSelecionados[2]}
							onChange={(event) => {
								const novoArray = [...saboresSelecionados];
								novoArray[2] = event.target.value;
								setSaboresSelecionados(novoArray);
							}}
							sx={{
								'@media screen and (max-width: 768px)': {
									width: '100%',
									marginBottom: 1,	
								}
							}}
						>
							<MenuItem value={'none'}>Selecione um sabor</MenuItem>
							{sabores.map((sabor) => (
								<MenuItem value={sabor.id}>{sabor.nome}</MenuItem>
							))}
						</Select>
					</Stack>
					
					<Typography align="center" variant="h4" sx={{marginTop: 4}}>Massa</Typography>
					<Stack
						direction="row"
						spacing={2}
						alignItems="center"
						justifyContent="center"
						sx={{
							marginTop: 2,
						}}
					>
						<Select
							label="massa"
							id="massa"
							value={massaSelecionada}
							onChange={(event) => {
								setMassaSelecionada(event.target.value);
							}}
							sx={{
								'@media screen and (max-width: 768px)': {
									width: '100%',	
								}
							}}
						>
							<MenuItem value={'none'}>Selecione uma massa</MenuItem>
							{massas.map((massa) => (
								<MenuItem value={massa.id}>{massa.nome}</MenuItem>
							))}
						</Select>
					</Stack>

					<Typography align="center" variant="h4" sx={{marginTop: 4}}>Borda</Typography>
					<Stack
						direction="row"
						spacing={2}
						alignItems="center"
						justifyContent="center"
						sx={{
							marginTop: 2,
						}}
					>
						<Select
							label="borda"
							id="borda"
							value={bordaSelecionada}
							onChange={(event) => {
								setBordaSelecionada(event.target.value);
							}}
							sx={{
								'@media screen and (max-width: 768px)': {
									width: '100%',	
								}
							}}
						>
							<MenuItem value={'none'}>Selecione uma borda</MenuItem>
							{bordas.map((borda) => (
								<MenuItem value={borda.id}>{borda.nome}</MenuItem>
							))}
						</Select>
					</Stack>
						
					<Stack
						direction="row"
						spacing={2}
						alignItems="center"
						justifyContent="center"
						sx={{
							marginTop: 4,
						}}
					>
						<Button
							variant="contained"
							color="primary"
							onClick={() => {
								const novaPizza = {
									sabores: saboresSelecionados,
									massa: massaSelecionada,
									borda: bordaSelecionada,
								};

								inserePizza(novaPizza);
							}}
						>
							Fazer pedido
						</Button>
					</Stack>
				</Card>
			</Stack>

			<Footer />
		</div>	
	)
}
